// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessorInfo.Repository.Data;

#nullable disable

namespace ProcessorInfo.Repository.Migrations
{
    [DbContext(typeof(ProcessorInfoDbContext))]
    [Migration("20240113203450_Initial_Data")]
    partial class Initial_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProcessorInfo.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Name = "INTEL"
                        },
                        new
                        {
                            BrandId = 2,
                            Name = "AMD"
                        },
                        new
                        {
                            BrandId = 3,
                            Name = "QUALCOMM"
                        });
                });

            modelBuilder.Entity("ProcessorInfo.Models.Chipset", b =>
                {
                    b.Property<int>("ChipsetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChipsetId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChipsetId");

                    b.ToTable("Chipset");

                    b.HasData(
                        new
                        {
                            ChipsetId = 1,
                            Name = "Z790"
                        },
                        new
                        {
                            ChipsetId = 2,
                            Name = "Z690"
                        },
                        new
                        {
                            ChipsetId = 3,
                            Name = "Z590"
                        },
                        new
                        {
                            ChipsetId = 4,
                            Name = "Z490"
                        },
                        new
                        {
                            ChipsetId = 5,
                            Name = "Z390"
                        },
                        new
                        {
                            ChipsetId = 6,
                            Name = "Z270"
                        },
                        new
                        {
                            ChipsetId = 7,
                            Name = "Z170"
                        },
                        new
                        {
                            ChipsetId = 8,
                            Name = "AM4"
                        },
                        new
                        {
                            ChipsetId = 9,
                            Name = "AM5"
                        },
                        new
                        {
                            ChipsetId = 10,
                            Name = "Mobile"
                        });
                });

            modelBuilder.Entity("ProcessorInfo.Models.Processor", b =>
                {
                    b.Property<int>("ProcessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("processor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessorId"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<double>("Cache")
                        .HasColumnType("float");

                    b.Property<int>("ChipsetId")
                        .HasColumnType("int");

                    b.Property<double>("EfficencyCores")
                        .HasColumnType("float");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("bit");

                    b.Property<double>("MaxTurboFrequency")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PerformanceCores")
                        .HasColumnType("float");

                    b.Property<int>("TotalThreads")
                        .HasColumnType("int");

                    b.HasKey("ProcessorId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ChipsetId");

                    b.ToTable("Processor");

                    b.HasData(
                        new
                        {
                            ProcessorId = 1,
                            BrandId = 1,
                            Cache = 36.0,
                            ChipsetId = 1,
                            EfficencyCores = 16.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.7999999999999998,
                            Name = "Intel Core i9-13900K",
                            PerformanceCores = 8.0,
                            TotalThreads = 32
                        },
                        new
                        {
                            ProcessorId = 2,
                            BrandId = 1,
                            Cache = 30.0,
                            ChipsetId = 2,
                            EfficencyCores = 8.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.5,
                            Name = "Intel Core i9-12900KS",
                            PerformanceCores = 8.0,
                            TotalThreads = 24
                        },
                        new
                        {
                            ProcessorId = 3,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 3,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.2000000000000002,
                            Name = "Intel Core i9-11900K",
                            PerformanceCores = 8.0,
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 4,
                            BrandId = 1,
                            Cache = 20.0,
                            ChipsetId = 4,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.2999999999999998,
                            Name = "Intel Core i9-10900K",
                            PerformanceCores = 10.0,
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 5,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 5,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-9900K",
                            PerformanceCores = 8.0,
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 6,
                            BrandId = 1,
                            Cache = 12.0,
                            ChipsetId = 5,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 4.7999999999999998,
                            Name = "Intel Core i9-8950HK",
                            PerformanceCores = 6.0,
                            TotalThreads = 12
                        },
                        new
                        {
                            ProcessorId = 7,
                            BrandId = 1,
                            Cache = 30.0,
                            ChipsetId = 1,
                            EfficencyCores = 8.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.4000000000000004,
                            Name = "Intel Core i9-13700K",
                            PerformanceCores = 8.0,
                            TotalThreads = 24
                        },
                        new
                        {
                            ProcessorId = 8,
                            BrandId = 1,
                            Cache = 25.0,
                            ChipsetId = 2,
                            EfficencyCores = 4.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-12700K",
                            PerformanceCores = 8.0,
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 9,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 3,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-11700K",
                            PerformanceCores = 8.0,
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 10,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 4,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0999999999999996,
                            Name = "Intel Core i9-10700K",
                            PerformanceCores = 8.0,
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 11,
                            BrandId = 1,
                            Cache = 12.0,
                            ChipsetId = 6,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 4.9000000000000004,
                            Name = "Intel Core i7-9700K",
                            PerformanceCores = 8.0,
                            TotalThreads = 8
                        },
                        new
                        {
                            ProcessorId = 12,
                            BrandId = 1,
                            Cache = 12.0,
                            ChipsetId = 6,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 4.7000000000000002,
                            Name = "Intel Core i7-8700K",
                            PerformanceCores = 6.0,
                            TotalThreads = 12
                        },
                        new
                        {
                            ProcessorId = 13,
                            BrandId = 1,
                            Cache = 30.0,
                            ChipsetId = 1,
                            EfficencyCores = 8.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 5.4000000000000004,
                            Name = "Intel Core i9-13700KF",
                            PerformanceCores = 8.0,
                            TotalThreads = 24
                        },
                        new
                        {
                            ProcessorId = 14,
                            BrandId = 1,
                            Cache = 25.0,
                            ChipsetId = 2,
                            EfficencyCores = 4.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-12700KF",
                            PerformanceCores = 8.0,
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 15,
                            BrandId = 2,
                            Cache = 72.0,
                            ChipsetId = 8,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 4.9000000000000004,
                            Name = "AMD Ryzen 9 5950X",
                            PerformanceCores = 16.0,
                            TotalThreads = 32
                        },
                        new
                        {
                            ProcessorId = 16,
                            BrandId = 2,
                            Cache = 81.0,
                            ChipsetId = 9,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 5.7000000000000002,
                            Name = "AMD Ryzen 9 7950X",
                            PerformanceCores = 16.0,
                            TotalThreads = 32
                        },
                        new
                        {
                            ProcessorId = 17,
                            BrandId = 2,
                            Cache = 60.0,
                            ChipsetId = 8,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 4.7000000000000002,
                            Name = "AMD Ryzen 7 5750X",
                            PerformanceCores = 10.0,
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 18,
                            BrandId = 3,
                            Cache = 6.7999999999999998,
                            ChipsetId = 10,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 2.8399999999999999,
                            Name = "Snapdragon 865 5G",
                            PerformanceCores = 8.0,
                            TotalThreads = 8
                        });
                });

            modelBuilder.Entity("ProcessorInfo.Models.Processor", b =>
                {
                    b.HasOne("ProcessorInfo.Models.Brand", "Brand")
                        .WithMany("Processors")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessorInfo.Models.Chipset", "Chipset")
                        .WithMany("Processors")
                        .HasForeignKey("ChipsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Chipset");
                });

            modelBuilder.Entity("ProcessorInfo.Models.Brand", b =>
                {
                    b.Navigation("Processors");
                });

            modelBuilder.Entity("ProcessorInfo.Models.Chipset", b =>
                {
                    b.Navigation("Processors");
                });
#pragma warning restore 612, 618
        }
    }
}
