// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessorInfo.Repository.Data;

#nullable disable

namespace ProcessorInfo.Repository.Migrations
{
    [DbContext(typeof(ProcessorInfoDbContext))]
    [Migration("20240117000015_Seed_with_pictures")]
    partial class Seed_with_pictures
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProcessorInfo.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Name = "INTEL",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/intel-new-logo-16x9.jpg.rendition.intel.web.1648.927.jpg"
                        },
                        new
                        {
                            BrandId = 2,
                            Name = "AMD",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/AMD_Logo.svg.png"
                        },
                        new
                        {
                            BrandId = 3,
                            Name = "QUALCOMM",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/mobile.jpg"
                        });
                });

            modelBuilder.Entity("ProcessorInfo.Models.Chipset", b =>
                {
                    b.Property<int>("ChipsetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChipsetId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChipsetId");

                    b.ToTable("Chipset");

                    b.HasData(
                        new
                        {
                            ChipsetId = 1,
                            Name = "Z790",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/z790-chipset-blockdiagram-4.png"
                        },
                        new
                        {
                            ChipsetId = 2,
                            Name = "Z690",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/z690.jpg"
                        },
                        new
                        {
                            ChipsetId = 3,
                            Name = "Z590",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/z590.jpg"
                        },
                        new
                        {
                            ChipsetId = 4,
                            Name = "Z490",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/Intel-Z490-Chipset-Diagram.jpg"
                        },
                        new
                        {
                            ChipsetId = 5,
                            Name = "Z390",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/z390.png"
                        },
                        new
                        {
                            ChipsetId = 8,
                            Name = "AM4",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/amd-b550-chipset-block-diagram.png"
                        },
                        new
                        {
                            ChipsetId = 9,
                            Name = "AM5",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/c11947df-28fa-44df-9c0f-55142218f797_6083x2097.jpg"
                        },
                        new
                        {
                            ChipsetId = 10,
                            Name = "Mobile",
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/mobile.jpg"
                        });
                });

            modelBuilder.Entity("ProcessorInfo.Models.Processor", b =>
                {
                    b.Property<int>("ProcessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("processor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessorId"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<double>("Cache")
                        .HasColumnType("float");

                    b.Property<int>("ChipsetId")
                        .HasColumnType("int");

                    b.Property<double>("EfficencyCores")
                        .HasColumnType("float");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("bit");

                    b.Property<double>("MaxTurboFrequency")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PerformanceCores")
                        .HasColumnType("float");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalThreads")
                        .HasColumnType("int");

                    b.HasKey("ProcessorId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ChipsetId");

                    b.ToTable("Processor");

                    b.HasData(
                        new
                        {
                            ProcessorId = 1,
                            BrandId = 1,
                            Cache = 36.0,
                            ChipsetId = 1,
                            EfficencyCores = 16.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.7999999999999998,
                            Name = "Intel Core i9-13900K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/13900k.jpg",
                            TotalThreads = 32
                        },
                        new
                        {
                            ProcessorId = 2,
                            BrandId = 1,
                            Cache = 30.0,
                            ChipsetId = 2,
                            EfficencyCores = 8.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.5,
                            Name = "Intel Core i9-12900KS",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/12900ks.jpg",
                            TotalThreads = 24
                        },
                        new
                        {
                            ProcessorId = 3,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 3,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.2000000000000002,
                            Name = "Intel Core i9-11900K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/11900k.jpg",
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 4,
                            BrandId = 1,
                            Cache = 20.0,
                            ChipsetId = 4,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.2999999999999998,
                            Name = "Intel Core i9-10900K",
                            PerformanceCores = 10.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/10900k.jpg",
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 5,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 5,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-9900K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/9900k.jpg",
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 6,
                            BrandId = 1,
                            Cache = 30.0,
                            ChipsetId = 1,
                            EfficencyCores = 8.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.4000000000000004,
                            Name = "Intel Core i9-13700K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/13700kf.jpg",
                            TotalThreads = 24
                        },
                        new
                        {
                            ProcessorId = 8,
                            BrandId = 1,
                            Cache = 25.0,
                            ChipsetId = 2,
                            EfficencyCores = 4.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-12700K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/12700k.jpg",
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 9,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 3,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0,
                            Name = "Intel Core i9-11700K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/11700k.jpg",
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 10,
                            BrandId = 1,
                            Cache = 16.0,
                            ChipsetId = 4,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 5.0999999999999996,
                            Name = "Intel Core i9-10700K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/10700k.jpg",
                            TotalThreads = 16
                        },
                        new
                        {
                            ProcessorId = 11,
                            BrandId = 1,
                            Cache = 12.0,
                            ChipsetId = 6,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 4.9000000000000004,
                            Name = "Intel Core i7-9700K",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/9700k.jpg",
                            TotalThreads = 8
                        },
                        new
                        {
                            ProcessorId = 13,
                            BrandId = 1,
                            Cache = 30.0,
                            ChipsetId = 1,
                            EfficencyCores = 8.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 5.4000000000000004,
                            Name = "Intel Core i9-13700KF",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/13700kf.jpg",
                            TotalThreads = 24
                        },
                        new
                        {
                            ProcessorId = 15,
                            BrandId = 2,
                            Cache = 72.0,
                            ChipsetId = 8,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 4.9000000000000004,
                            Name = "AMD Ryzen 9 5950X",
                            PerformanceCores = 16.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/743796831.amd-ryzen-9-5950x-16-core-3-4ghz-am4-box-without-fan-and-heatsink.jpg",
                            TotalThreads = 32
                        },
                        new
                        {
                            ProcessorId = 16,
                            BrandId = 2,
                            Cache = 81.0,
                            ChipsetId = 9,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 5.7000000000000002,
                            Name = "AMD Ryzen 9 7950X",
                            PerformanceCores = 16.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/7950X.jpg",
                            TotalThreads = 32
                        },
                        new
                        {
                            ProcessorId = 17,
                            BrandId = 2,
                            Cache = 60.0,
                            ChipsetId = 8,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = false,
                            MaxTurboFrequency = 4.7000000000000002,
                            Name = "AMD Ryzen 7 5750X",
                            PerformanceCores = 10.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/5750X.jpg",
                            TotalThreads = 20
                        },
                        new
                        {
                            ProcessorId = 18,
                            BrandId = 3,
                            Cache = 6.7999999999999998,
                            ChipsetId = 10,
                            EfficencyCores = 0.0,
                            IntegratedGraphics = true,
                            MaxTurboFrequency = 2.8399999999999999,
                            Name = "Snapdragon 865 5G",
                            PerformanceCores = 8.0,
                            PhotoUrl = "https://processorinfostorageacc.blob.core.windows.net/processorinfo/snapdragon.jpg",
                            TotalThreads = 8
                        });
                });

            modelBuilder.Entity("ProcessorInfo.Models.SiteUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProcessorInfo.Models.Processor", b =>
                {
                    b.HasOne("ProcessorInfo.Models.Brand", "Brand")
                        .WithMany("Processors")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessorInfo.Models.Chipset", "Chipset")
                        .WithMany("Processors")
                        .HasForeignKey("ChipsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Chipset");
                });

            modelBuilder.Entity("ProcessorInfo.Models.SiteUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("ProcessorInfo.Models.SiteUser", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProcessorInfo.Models.Brand", b =>
                {
                    b.Navigation("Processors");
                });

            modelBuilder.Entity("ProcessorInfo.Models.Chipset", b =>
                {
                    b.Navigation("Processors");
                });
#pragma warning restore 612, 618
        }
    }
}
